import './globals.css';
import Navbar from '../components/Navbar';
import { getCurrentUser } from '@/lib/session';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        {user && <Navbar user={user} />}
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
